### PR TITLE
Set default for split_tunnel config

### LINKED ISSUE #101: [BUG] Don't Work Kill Switch
**Describe the bug**
In this update, we restored the program's functionality(thank you for that!), but broke the KillSwitch. When you select it, the program breaks down and displays this

```
Traceback (most recent call last):
  File "/usr/bin/protonvpn", line 8, in <module>
    sys.exit(main())
  File "/usr/lib64/python3.8/site-packages/protonvpn_cli/cli.py", line 73, in main
    cli()
  File "/usr/lib64/python3.8/site-packages/protonvpn_cli/cli.py", line 143, in cli
    configure_cli()
  File "/usr/lib64/python3.8/site-packages/protonvpn_cli/cli.py", line 340, in configure_cli
    set_killswitch()
  File "/usr/lib64/python3.8/site-packages/protonvpn_cli/cli.py", line 590, in set_killswitch
    if killswitch and int(get_config_value("USER", "split_tunnel")):
  File "/usr/lib64/python3.8/site-packages/protonvpn_cli/utils.py", line 122, in get_config_value
    return config[group][key]
  File "/usr/lib64/python3.8/configparser.py", line 1254, in __getitem__
    raise KeyError(key)
KeyError: 'split_tunnel'
```

**Desktop (please complete the following information):**
 - OS: Slackware Current
 - Python Version: 3.8.1
 - ProtonVPN-CLI Version: 2.2.1

### PR DESCRIPTION
**Pull request by lgommans**
Fixes #101

### CODE REVIEW

**Comment by lgommans** [comment]
Note that this won't fix existing configurations, only new ones. As for fixing existing installations, there are possible two ways to go:

- Check whether the configuration key exists before reading it, every single time you want to read a config value somewhere in the code, and litter the code with default assumptions.
- Change the code such that the defaults are baked into the configuration reader and existing keys are overwritten by the values in the config file. This makes it unnecessary to needlessly write the default configuration values on initialization, makes upgrading default configuration choices easier/possible (since you don't have to migrate existing configs, and you know which values were default and can be safely changed versus which ones were an explicit user preference), and it simplifies the code not to have to codify default behaviour for nonexistent keys everywhere... but this is just my personal preference.

Since this is a more architectural code change than just fixing the issue at hand, I'll leave that choice up to you. I'd be happy to implement the latter option if desired.

**Comment by Rafficer** [comment]
Thank you.

Your code changes things that aren't relevant to this PR. Please change that.

I'll probably fix the issue at hand by changing up [this function](https://github.com/ProtonVPN/protonvpn-cli-ng/blob/31d1dcc89cdac8abde4c19b837a3ae4a83a02bda/protonvpn_cli/utils.py#L434) to set default configurations.

**Comment by lgommans** [comment]
Wait... that second commit is indeed completely irrelevant, I didn't open a pull request for that yet on purpose :|

Seems like github adds crap from your local repository if the changes are pushed to the same branch? TIL. Sorry 'bout that.

Do you know how to remove it? There is no UI button for it, and removing and re-creating the branch seems like it would probably do other weird things to this pull request.

**Comment by Rafficer** [comment]
Easiest thing to do would be to just note those changes and then remove the last commit from this branch. Then add the changes manually to another branch again.

1. `git rebase -i HEAD~2`

    This should open your text editor
2. On the second commit (should be the lower of the two) replace the word `pick` with `drop`.

    image

3. Save and close the editor.

4. `git log --oneline` should now show that only the latest commit is in this branch.

5. Run `git push origin master -f` to fore-push to github and removing the other commit there as well.

6. Never work on master when you're not the only one working on a project. And especially **never** PR from master to prevent this from happening :)

**Comment by lgommans** [comment]
Done!

**Comment by Rafficer** [comment]
Thanks again for you contribution. But I've fixed this issue more persistently in #104, hence I'll be closing this. 🙂

**Pull request closed without merging**
