### PR TITLE
Refactor country_codes and remove name_to_cc

### PR DESCRIPTION
**Pull request by karmadonov**
I removed `name_to_cc` from country_codes and added small improvements to `get_country_name`.

Also I added a few simple unittests for `get_country_name`, I hope it's ok? I also could add some tests for another parts of code, if you are ok with it.

To run tests you could use: `python -m unittest discover -v`

There is screenshots of connect and status, looks like all works fine:
country_codes
status

### CODE REVIEW

**Comment by Rafficer** [comment]
The tests shouldn't be in this PR, should they?

Adding tests for **only** 2 functions that are barely used seems a bit weird to me. At some point there should be tests, yeah, but for pretty much everything. I don't know what best to use for that, yet.

Please remove the tests. Rest looks good.

**Comment by Rafficer** [comment]
Thanks. I'll check everything myself before I approve it, but I don't think there are any issues.

I hope I got some time to work on this (and other parts of the project) later this week. :slightly_smiling_face:

**Comment by karmadonov** [comment]
Done.

p.s. If you want I could try to cover the project with unit tests and add some test coverage with an additional pull request if you are interested in it. I know `unittest` and `pytest`, so could use one that you choose. And I have a long advent of code next week :)

**Comment by Rafficer** [comment]
I'll come back at you for that :)

**Comment by Rafficer** [comment]
@kaplun Please squash merge :)

**Comment by Rafficer** [comment]
@karmadonov Can you please contact me via Email? You can find my Email on my Github profile.

It's about adding tests :)

**Pull request merged**
